//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoruHazirla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public Kullanici()
        {
            this.Sinavlar = new HashSet<Sinavlar>();
        }
    
        public string KullaniciAdi { get; set; }
        public string Parola { get; set; }
    
        public virtual ICollection<Sinavlar> Sinavlar { get; set; }
    }
}
